### ISSUE TITLE
beta 5 bug

### ISSUE THREAD

**Issue by Damien3131** [dero-am/astrobwt-miner#4] opened 2023-03-25 09:14 UTC
Hello

I already read about on discord but I confirm I have random bugs on beta 5 (program closes after a while).

best regards

**Comment by dero-am** [comment] 2023-03-25 11:09
@Damien3131 hello there, please give more detail:
- OS
- Chip type and RAM
- Roughly how long until it gets crashed?

**Comment by Damien3131** [comment] 2023-03-25 19:06
Windows 11
AMD ryzen '5800h) and epyc '7551) and threadripper (2990wx)
Delay to crash is very ransom but not immediate, few hours ?

**Comment by Alarmod** [comment] 2023-03-26 21:32
Windows 10 22H2 + AMD Epyc 7642 (48 cores) - ALL OK

**Comment by Damien3131** [comment] 2023-03-26 22:06
I have gone to beta 4 all OK, beta 5 sometimes the miner closes.

**Comment by dero-am** [comment] 2023-03-27 09:44
we've just released v1.9 that fixed several bugs that caused crash. Please try.
@Damien3131

**Comment by Alarmod** [comment] 2023-03-27 20:51
Errors with v1.9:

1.
6C140000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl\record\rec_layer_s3.c:309:

2.
Could not resolve/verify community pool (51.89.97.51)! Please check your connection.astrominer exited with code 1, if you want to exit astrominer, press Ctrl+C one more time

3. 
On start with 48+48 CPU (two NUMA nodes, 48 - Node 0 and 48 - Node 1) miner start only 48 threads attached to first NUMA node

4. 
Start with admin rights from the folder with Cyrillic symbols causes a start error

**Comment by Alarmod** [comment] 2023-03-27 21:09
Fix 2 with openssl-1.1.1t-win64.zip
Maybe You add option to disable autorun on all nodes (old mode support)?

**Comment by dero-am** [comment] 2023-03-28 09:36
@Alarmod  
(1) This error caused by (A) poor internet connection during verifying step (B) or the IP(s) are blocked/restricted by you or your internet provider or (C) some data packet couldn't get through your firewall.
(2) same as (1)
(3) should be resolved in v1.9. I have tested in a few machine and it worked. Please give me your command to check.
(4) This is expected on Windows. Please use alphabet folder by now.

**Comment by Alarmod** [comment] 2023-03-28 10:02
Variant 1: 
without -m, program automatically run 48 threads on node 0

Variant 2:
-m 96, program run 96 threads on the cores 0 ... 79, cores 80 ... 95 are unused. Cores 0 ... 63 attached to Node 0, 64 ... 95 to Node 1.

**Comment by dero-am** [comment] 2023-03-28 13:23
@Alarmod are you using v1.9?
I see that you are using 2 different CPUs on your dual board, which is the case that I have not tested yet (because I don't have the hardware and sadly I can't rent it from anyone)

There is a workaround for your case at the moment:
```
start /node 0 astrominer.exe -m 64 -w wallet -r host
start /node 1 astrominer.exe -m 32 -w wallet -r host
```
you'll need to run 2 miner instances

**Comment by Alarmod** [comment] 2023-03-28 13:27
I use v1.9
No, I have only one CPU with 96 threads, this CPU show as two NUMA-nodes 48 + 48.

**Comment by Alarmod** [comment] 2023-03-28 13:31
If i run 
start /node 0 astrominer.exe -m 64 -w wallet -r host
start /node 1 astrominer.exe -m 32 -w wallet -r host

all CPU threads run on the Node 0 :)

Older version work on Node 0 and Node 1

**Comment by dero-am** [comment] 2023-03-29 08:37
@Alarmod I see, what is your windows version and what chip is that?
I run astrominer on 3990X and it uses all 128 cores. not sure what I miss there tbh.

**Comment by Alarmod** [comment] 2023-03-29 15:42
Windows 10 22H2 + AMD Epyc 7642 (48 cores), configured as two Numa-nodes 48+48

**Comment by Alarmod** [comment] 2023-03-29 15:49
For example, xmrig work fine with all cores, maybe exist debug version to print debug info?

**Comment by dero-am** [comment] 2023-04-01 03:48
we aim to do a single universal code that applies to all OSes, we will try to find hardware to fix this issue, feel free to open it again.

**Closed as completed by dero-am** 2023-04-01 03:48 UTC
